function fig = ide_prepwin()
	close;
	color = 0.98; %0.313725490196078;
	fig = figure(...
		'Color',[color color color],...
		%'WindowState','maximized',...
		%'Position',[0 0 1 1],...
		%'OuterPosition',[0 0 1 1],...
		'Name','RPT Labs',...
		'NumberTitle','off',...
		'MenuBar','none',...
		'ToolBar','none');
	%axes('off');
	pos = get(0,'screensize');
	%pos(1) = pos(3)*0.005;
	pos(2) = pos(4)*0.06;
	%pos(3) = pos(3)*0.99;
	pos(4) = pos(4)*0.9;
	figure(fig,'Position',pos);
	%set(gca,'WindowState','maximized');
	pause(0.1);
	hold off;
end
