% OA3D_PWA
% Roberto Plácido Teixeira
% pwa_style(): style for OA3D_PWA html pages

function st = pwa_style()
	%html_bstyle();
	str = [ ...
		"<style>", ...
		".div-n {", ...
		"	border: 1px solid #f00;", ...
		"	padding: 5px;", ...
		"	margin: 5px;", ...
		"}", ...
		".div-l {", ...
		"	border: 1px solid #0f0;", ...
		"	padding: 5px;", ...
		"	margin: 5px;", ...
		"}", ...
		".div-m {", ...
		"	border: 1px solid #00f;", ...
		"	padding: 5px;", ...
		"	margin: 5px;", ...
		"}", ...
		".orb img, .equ img {", ...
		"	max-width: 100%%;", ...
		"}", ...
		".pwa-equ-td {", ...
		"	width: 600px;", ...
		"}" ...
		"</style>"
	];
	html_say(str)
	%html_estyle();
end
